# /etc/ysfgateway for WY6Y CyberFusion
[General]
Callsign=WY6Y
Suffix=ND
RptAddress=127.0.0.1
RptPort=3200
LocalAddress=127.0.0.1
LocalPort=4200
WiresXCommandPassthrough=0
Debug=1

[Info]
RXFrequency=438800000
TXFrequency=438800000
Power=1
Latitude=35.47
Longitude=-97.52
Height=5
Name=Hotspot
Description=CyberFusion YSF Hotspot

[Log]
DisplayLevel=1
FileLevel=2
FilePath=/var/log/ysfgateway
FileRoot=YSFGateway

[MQTT]
Address=127.0.0.1
Port=1883
Name=ysf-gateway

[Network]
Startup=ZZ Parrot
InactivityTimeout=10
Revert=0
Reconnect=1

[YSF Network]
Enable=1
Port=42000
Hosts=/usr/local/etc/YSFHosts-min.json
ReloadTime=60
ParrotAddress=127.0.0.1
ParrotPort=42012

[FCS Network]
Enable=0

[Remote Commands]
Enable=1
Port=6073
Password=
